from enum import Enum

class AgentCategory(str, Enum):
    INPUT = "input"
    EMBEDDINGS = "embeddings"
    LLM = "llm"
    TTS = "tts"
    STT = "stt"
    ITT = "itt"
    TTI = "tti"
    ITI = "iti"
    ITV = "itv"
    WEB = "web"
    MISC = "misc"
    THREE_DIMENSIONAL = "3d"
    API = "api"

class AgentSubcategory(str, Enum):
    EMBEDDING = "embedding"
    LLM_SIMPLE = "llm-simple"
    LLM_CHAT = "llm-chat"
    ITT = "itt"
    TTI = "tti"
    ITV = "itv"
    UPSCALE = "upscale"
    SKETCH = "sketch"
    STRUCTURE = "structure"
    ERASE = "erase"
    INPAINT = "inpaint"
    OUTPAINT = "outpaint"
    SEARCH_AND_REPLACE = "search-and-replace"
    SEARCH_AND_RECOLOR = "search-and-recolor"
    REMOVE_BACKGROUND = "remove-background"
    IMAGE_RESIZE = "image-resize"
    THREE_DIMENSIONAL = "3d"
    MY_AGENTS = "myAgents"